### ISSUE TITLE
fails if postinstallDev is missing

### ISSUE THREAD

**Issue by jantimon** [sachinraja/yarn-plugin-postinstall-dev#2]
unfortunately this plugin fails if there is no postinstallDev

**Comment by sachinraja** [comment]
Reading from package.json could solve this too because we can just check if it exists before executing the command.

**Comment by sachinraja** [comment]
fixed in https://github.com/sachinraja/yarn-plugin-postinstall-dev/commit/070c4e38dea0d1eb40d00d93db638172bb8f4e6b
